### ISSUE TITLE
Slice operator

### ISSUE THREAD

**Issue by andrewrogow** [rahulsekar/brautopy#2]
https://github.com/rahulsekar/brautopy/blob/aadc88e5e58d643566382a16949c7c75eee3a7a9/server.py#L44 

Why do you do `data[0] + data[1]`? 
in your case this makes no sense. Use slice. `data[:2]`

**Comment by rahulsekar** [comment]
@andrewrogow Thank you, I was a python newbie then. Now I think ```.startswith``` is better. Fixed this, some formatting and a bug affecting Chrome.
